# Generated by Django 3.2 on 2021-04-26 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Стaтусы',
            },
        ),
    ]
