# Generated by Django 3.2 on 2021-05-17 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.CASCADE, related_name='task_performer', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
